const WHATSAPP="9779807088460";
const products=[
["diamonds-50","50 Diamonds",70,"diamonds","💎"],["diamonds-115","115 Diamonds",120,"diamonds","💎"],["diamonds-240","240 Diamonds",250,"diamonds","💎"],["diamonds-610","610 Diamonds",550,"diamonds","💎"],
["level-all","Level Up Pass — All Levels",650,"passes","🎫"],["level-6","Level 6",75,"passes","🎫"],["level-10","Level 10",130,"passes","🎫"],["level-15","Level 15",130,"passes","🎫"],["level-20","Level 20",130,"passes","🎫"],["level-25","Level 25",130,"passes","🎫"],["level-30","Level 30",170,"passes","🎫"],
["weekly-lite","Weekly Lite",100,"weekly","📅"],["weekly","Weekly",230,"weekly","📅"],["monthly","Monthly",1150,"monthly","🗓️"],["weekly-monthly","Weekly + Monthly",1350,"monthly","🔥"],["combo-all","Weekly + Monthly + Weekly Lite",1450,"monthly","🔥"]];
let selected=null;
const money=n=>"Rs. "+n.toLocaleString("en-IN");
function render(cat="all"){grid.innerHTML=products.filter(p=>cat==="all"||p[3]===cat).map(p=>`<article class="product"><div class="icon">${p[4]}</div><h3>${p[1]}</h3><p>Available for order</p><div class="price">${money(p[2])}</div><button class="buy" onclick="choose('${p[0]}')">Buy Now</button></article>`).join("")}
function choose(id){selected=products.find(p=>p[0]===id);document.getElementById("selected").innerHTML=`${selected[4]} ${selected[1]} <span>• ${money(selected[2])}</span>`;document.getElementById("checkout").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.cat)});
document.getElementById("form").onsubmit=e=>{e.preventDefault();if(!selected){alert("Please select a package first.");return}const uid=document.getElementById("uid").value.trim(),name=document.getElementById("name").value.trim()||"Not provided",payment=document.querySelector('input[name="payment"]:checked').value,ref=document.getElementById("ref").value.trim(),id="VZ-"+Date.now().toString().slice(-6);const msg=`*VIZUKA TOPUP ORDER*\n\nOrder ID: ${id}\nPackage: ${selected[1]}\nPrice: ${money(selected[2])}\nPlayer UID: ${uid}\nName: ${name}\nPayment: ${payment}\nPayment Reference: ${ref}\n\nI have completed the payment. Please verify my order.`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,"_blank")};
render();