const KEY="vizuka_products_v2";const DEFAULT=[{"id": "p1", "name": "50 💎", "category": "Diamonds", "price": 70, "available": true}, {"id": "p2", "name": "115 💎", "category": "Diamonds", "price": 120, "available": true}, {"id": "p3", "name": "240 💎", "category": "Diamonds", "price": 250, "available": true}, {"id": "p4", "name": "610 💎", "category": "Diamonds", "price": 550, "available": true}, {"id": "p5", "name": "Level Up Pass — Level 6", "category": "Level Up Pass", "price": 75, "available": true}, {"id": "p6", "name": "Level Up Pass — Level 10", "category": "Level Up Pass", "price": 130, "available": true}, {"id": "p7", "name": "Level Up Pass — Level 15", "category": "Level Up Pass", "price": 130, "available": true}, {"id": "p8", "name": "Level Up Pass — Level 20", "category": "Level Up Pass", "price": 130, "available": true}, {"id": "p9", "name": "Level Up Pass — Level 25", "category": "Level Up Pass", "price": 130, "available": true}, {"id": "p10", "name": "Level Up Pass — Level 30", "category": "Level Up Pass", "price": 170, "available": true}, {"id": "p11", "name": "Level Up Pass — All Levels", "category": "Level Up Pass", "price": 650, "available": true}, {"id": "p12", "name": "Weekly Lite", "category": "Memberships", "price": 100, "available": true}, {"id": "p13", "name": "Weekly", "category": "Memberships", "price": 230, "available": true}, {"id": "p14", "name": "Monthly", "category": "Memberships", "price": 1150, "available": true}, {"id": "p15", "name": "Weekly + Monthly", "category": "Combo", "price": 1350, "available": true}, {"id": "p16", "name": "Weekly + Monthly + Weekly Lite", "category": "Combo", "price": 1450, "available": true}];let products=JSON.parse(localStorage.getItem(KEY)||"null")||DEFAULT;
const grid=document.querySelector("#grid"),filters=document.querySelector("#filters");let selected;
const cats=["All",...new Set(products.map(x=>x.category))];
filters.innerHTML=cats.map((x,i)=>`<button class="filter ${i?"":"active"}" data-cat="${x}">${x}</button>`).join("");
function render(cat="All"){grid.innerHTML=products.filter(x=>cat==="All"||x.category===cat).map(x=>`<article class="card"><span class="cat">${x.category}</span><h3>${x.name}</h3><div class="price">Rs. ${Number(x.price).toLocaleString()}</div><button class="btn full ${x.available?"":"off"}" ${x.available?"":"disabled"} data-id="${x.id}">${x.available?"Buy Now":"Unavailable"}</button></article>`).join("");
grid.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>open(products.find(x=>x.id===b.dataset.id)))}
filters.onclick=e=>{if(!e.target.dataset.cat)return;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");render(e.target.dataset.cat)};
function open(p){selected=p;document.querySelector("#pname").textContent=p.name;document.querySelector("#pprice").textContent="Rs. "+Number(p.price).toLocaleString();document.querySelector("#modal").classList.remove("hidden")}
document.querySelector("#close").onclick=()=>document.querySelector("#modal").classList.add("hidden");
document.querySelector("#form").onsubmit=e=>{e.preventDefault();const id="VZ-"+Math.random().toString(36).slice(2,8).toUpperCase();const o={orderId:id,product:selected.name,price:selected.price,uid:uid.value,paymentMethod:method.value};localStorage.setItem("vizuka_last_order",JSON.stringify(o));alert("Order "+id+" created.\n\nPayment screen/backend will be connected in the next phase.");document.querySelector("#modal").classList.add("hidden");e.target.reset()};
render();